default: &default
  adapter:  postgresql
  encoding: unicode
  host:     <%= ENV.fetch('PG_HOST',  'localhost') %>
  port:     <%= ENV.fetch('PG_PORT', 5432) %>
  username: <%= ENV.fetch('PG_USER', Rails.application.credentials.dig(:database, :username)) %>
  password: <%= ENV.fetch('PG_PASSWORD', Rails.application.credentials.dig(:database, :password)) %>
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout:  5000

development:
  <<: *default
  database: polyclinic_management_development

test:
  <<: *default
  database: polyclinic_management_test

production:
  <<: *default
  database: polyclinic_management_production
